services:
  - type: web
    name: cuaca-bmkg-api
    env: python
    plan: free
    region: singapore
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -b 0.0.0.0:8000 app:app"
   
